name: stan-moodle

services:
  database:
    container_name: moodle_db
    image: postgres:14.18
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - moodle-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  web:
    container_name: php_for_moodle
    build:
      context: ./moodle
    restart: always
    volumes:
      - ./moodle/srcs:/var/www/html
      - ./moodledata:/var/www/moodledata
      - ./php-conf/moodle.ini:/usr/local/etc/php/conf.d/moodle.ini:ro
    networks:
      - moodle-net
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  pgdata:

networks:
  moodle-net:
    driver: bridge
